"""
--------------------------------------------------------------------------------
-------------------------------- Mist MCP SERVER -------------------------------

    Written by: Thomas Munzer (tmunzer@juniper.net)
    Github    : https://github.com/tmunzer/mistmcp

    This package is licensed under the MIT License.

--------------------------------------------------------------------------------
"""

from enum import Enum


class McpToolsCategory(Enum):
    SELF_ACCOUNT = "self_account"
    UTILITIES_UPGRADE = "utilities_upgrade"
    ORGS_NAC = "orgs_nac"
    MARVIS = "marvis"
    DEVICES = "devices"
    CONFIGURATION = "configuration"
    SLES = "sles"
    SITES_INSIGHTS = "sites_insights"
    CONSTANTS = "constants"
    WRITE = "write"
    WRITE_DELETE = "write_delete"
    EVENTS = "events"
    INFO = "info"
    STATS = "stats"
    UTILITIES = "utilities"


TOOLS = {
    "configuration": {
        "description": "Configuration related objects for the sites and organizations. It provides access to various configuration objects such as site settings, device profiles, and more. These objects can be used to configure the network in a consistent manner.",
        "tools": ["mist_get_configuration"],
    },
    "constants": {
        "description": "Constants are read-only values and definitions used across the Juniper Mist platform. They include predefined lists of device models, alarm types, and other standardized values that are referenced throughout the API.",
        "tools": ["mist_describe"],
    },
    "devices": {
        "description": "Devices are any Network device managed or monitored by Juniper Mist. It can be * Wireless Access Points * Juniper Switch (EX, QFX) * Juniper WAN Gateway (SRX, SSR) * Mist Edges * Other or 3rd party devices, like Cradlepoint Devices. Mist provides many ways (device_type specific template, site template, device profile, per-device) to configure devices for different kind of scenarios.\n\nThe precedence goes from most specific to least specific\n\nDevice > Device Profile > RFTemplate (for AP only) > DeviceType-specific Template > Site Template > Site Setting",
        "tools": ["mist_search_assets"],
    },
    "events": {
        "description": "Events related to the sites and organizations. It provides access to various events such as device events, client events, and more. These events can be used for monitoring and troubleshooting purposes.",
        "tools": ["mist_search_activity"],
    },
    "info": {
        "description": "Tools that provide information about the sites and organizations.",
        "tools": ["mist_get_next_page"],
    },
    "marvis": {
        "description": "Marvis is a virtual network assistant that provides insights and analytics for the Mist network. It can be used to analyze network performance, troubleshoot issues, and optimize network configurations.\n\nIt includes features such as synthetic tests, which allow users to simulate network traffic and measure performance metrics.",
        "tools": ["mist_troubleshoot"],
    },
    "orgs_nac": {
        "description": "NAC related objects for the organizations. It provides access to NAC Endpoints, NAC fingerprints, tags, and rules.",
        "tools": ["mist_search_security"],
    },
    "self_account": {
        "description": "tools related to the currently connected user account.",
        "tools": ["mist_get_account"],
    },
    "sites_insights": {
        "description": "Insights related objects for the sites. It provides access to site insights and insight metrics. Site insights are generated by Mist AI to provide actionable information about the network performance and user experience.",
        "tools": ["mist_get_site_insights"],
    },
    "sles": {
        "description": "SLEs, or Service-Level Expectations, are metrics used to monitor and report on the user experience of a Wireless, Wired or Wan network.\\n\\nThey are generated through data science and machine learning algorithms and provide insights into various aspects of the network, such as coverage, capacity, connectivity, and performance.\\n\\nMist SLEs help identify when users do not have sufficient network quality, when they face issues with connecting or roaming between access points, and when there are problems on the wired network.\\n\\n SLEs API Calls at the MSP level can be used to retrieve the SLEs summary for each Organization attached to the MSP account.",
        "tools": ["mist_get_sle"],
    },
    "stats": {
        "description": "Tools that provide various statistics about the organizations, sites, devices, clients, ports and more.",
        "tools": ["mist_get_stats"],
    },
    "utilities": {
        "description": "Utility tools that provide various helper functions for the sites and organizations. These tools can be used for tasks such as searching, filtering, and formatting data.",
        "tools": ["mist_utilities"],
    },
    "utilities_upgrade": {
        "description": "tools used to manage device upgrades for a single device, at the site level or at the organization level.",
        "tools": ["mist_upgrades"],
    },
    "write": {
        "description": "Tools that perform write operations, such as creating, updating, or deleting resources in the Juniper Mist platform. These tools allow users to modify configurations, manage devices, and perform other actions that change the state of the network.",
        "tools": ["mist_update_configuration_objects"],
    },
    "write_delete": {
        "description": "Tools that perform both write and delete operations. These tools allow users to create, update, and delete resources in the Juniper Mist platform, providing more flexibility in managing the network configurations and resources.",
        "tools": ["mist_change_configuration_objects"],
    },
}
